# Generated by Django 4.2.5 on 2023-10-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TimeField(max_length=50000)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
